### ISSUE TITLE
floating point comparison

### ISSUE THREAD

**Issue by mikedilger** [PistonDevelopers/wavefront_obj#29]
0.00001 may not be the best choice of epsilon.  In fact, the right choice depends highly on how big or small the floats to be compared are. A better solution would be to compare against a fixed number of floating point representation separations (e.g.: If only 2 other floats are between these comparands, lets call them equal)

For this, I have a published a crate "float-cmp" at crates.io and at https://github.com/mikedilger/float-cmp .  I'm finding multiple crates which define their own 'fuzzy' equality, and it's time we came to a unified way of doing it.   It is based on my reading of https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/, and I'm very open to suggestions and changes (pull requests).

There are several ways to use it, and I wanted your input before I proposed a pull request for this.

Option 1 (sloppy but convenient):
Continue using PartialEq even though approximate equality is NOT transitive and thus strictly speaking is NOT a partial equivalence relation.   Define a fixed `ulps` of perhaps 8.  Continue to allow consumers of the Vertex struct to compare with language operators like "==", "<", etc.

Option 2 (correct but not as convenient):
Dump the idea of PartialEq, PartialOrd for vertex because we will approx compare, and that doesn't fit the definition proper.  As such dump use of the language operators like "==" and "<".  In doing so, we are able to expose the `ulps` parameter and users can pass in whatever works for their use case, e.g.   a.approx_eq(&b,10)

**Comment by cgaebel** [comment]
As far as I know, floating point comparison is only done in tests. Have you found any in non-test code?

**Comment by mikedilger** [comment]
Ah well, then no big deal.  I just noticed the function and thought I'd make the comment since I had just refactored my floating point work into a separate crate.
