### ISSUE TITLE
Add bvssvni as owner on crates.io

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/wavefront_obj#32]
I'm starting to write libraries on top of wavefront_obj, so I'd like to help keeping the crates.io version updated.

cc @cgaebel

**Comment by cgaebel** [comment]
Aren't you part of PistonDevelopers already?

**Comment by bvssvni** [comment]
Yes, but the crates.io owner system is decoupled from Github.

**Comment by cgaebel** [comment]
What's your login?

**Comment by bvssvni** [comment]
bvssvni

**Comment by cgaebel** [comment]
Done.
