### ISSUE TITLE
Incorrect documentation about the location of the vertex indices.

### ISSUE THREAD

**Issue by Marckvdv** [PistonDevelopers/wavefront_obj#42]
In the documentation of `Object`, the following documentation is supplied for the `vertices` member:

> vertices: The set of vertices this object is composed of. These are referenced by index in `faces`.

This `faces` member is not mentioned anywhere in the library (as far is I can tell), perhaps it meant to be `geometry.shapes`? This is the actual location of the vertex indices.

**Comment by cgaebel** [comment]
Thanks for the report!

If you send a pull request, I'll merge it! Otherwise, it'll probably be fixed in the next day or two.

**Comment by Marckvdv** [comment]
There you go, a pull request  for you!

**Comment by cgaebel** [comment]
It's been merged. This is now fixed.
