### ISSUE TITLE
Faster lexer without dynalloc

### ISSUE THREAD

**Issue by phaazon** [PistonDevelopers/wavefront_obj#49]
Currently, the lexer allocates a `String` for every new token – I think it actually even allocates when doing a lookahead with `peek` :(.

I don’t know whether you have code to fix that yet, but if you don’t, I can help by writing the patch, even though it’s not a one priority now. :)

**Comment by cgaebel** [comment]
I would love a patch to fix it. How much i love the patch depends on how
hairy the resulting code gets. Ideally it'd be no uglier than it is now.

**Comment by phaazon** [comment]
Hehe, sounds legit :).

**Comment by phaazon** [comment]
Closing as it was implemented by #57.
