### ISSUE TITLE
3Ds Max exports fail; likely to be linked to order of parsing

### ISSUE THREAD

**Issue by phaazon** [PistonDevelopers/wavefront_obj#51]
The parsing order might be dependent on the way the parser expects tokens to appear.

**Comment by cgaebel** [comment]
?

**Comment by phaazon** [comment]
I cannot load obj exported from 3Ds Max, because the order / abscence of some keys make the parser fail. For instance, unnamed objects (no o) causes an error when reading the first vertex. Or the normals come after the texture coordinates (or the other way around, I don’t quit remember), making the parser fail as well.

**Comment by cgaebel** [comment]
Can you attach an minimal-ish example?

**Comment by phaazon** [comment]
The example I tested on is 45MB big, so… not yet :D. But looking at the parser, I guess there’s something wrong with the order the parser expects things to occur.

**Comment by phaazon** [comment]
Though:

```
```

> `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ParseFailed(ParseError { line_number: 10, message: "Expected end of input but got v." })', ../src/libcore/result.rs:799`

**Comment by phaazon** [comment]
Ok, looks like it’s a problem with unammed object. I’ll fix that.

**Comment by phaazon** [comment]
Ok, I fixed the problem with objects. Now I have another problem. Fixing it as well.
