### ISSUE TITLE
Parser loads forever

### ISSUE THREAD

**Issue by doxxx** [PistonDevelopers/wavefront_obj#56]
I'm trying to load a simple obj file of the Suzanne monkey head exported from Blender. `wavefront::obj::parse` loads forever -- I gave up after a few minutes with the process at 7GB of memory.

I've tried with both debug and release mode binaries.

Here's the obj file:
[monkey.zip](https://github.com/PistonDevelopers/wavefront_obj/files/1186010/monkey.zip)

Using wavefront_obj 5.1.0 with rust 1.19.

**Comment by doxxx** [comment]
I tried again after ensuring that the quads in the object were converted to triangles, but it still loaded forever.

[monkey2.zip](https://github.com/PistonDevelopers/wavefront_obj/files/1186021/monkey2.zip)

**Comment by phaazon** [comment]
I had the same issue with a mesh exported from Cinema4D. Issue was #54.

**Comment by themasch** [comment]
I always got a "out of memory" for .obj files containing mtl references, even a simple cube with 8 vertices and 12 triangles. when I remove the mtl references, it works.

**Comment by doxxx** [comment]
Thanks I'll try that.

**Comment by LaylConway** [comment]
Perhaps the same parser bug that previously affected .obj files also affects .mtl files?

**Comment by doxxx** [comment]
I tried removing the mtl reference from my object and I still get the same problem.

**Comment by doxxx** [comment]
My bad, I was being dumb. `wavefront_obj::obj::parse(String)` doesn't expect the file _path_, it expects the file _contents_.
