### ISSUE TITLE
obj::parse() never returns

### ISSUE THREAD

**Issue by NickDriscoll** [PistonDevelopers/wavefront_obj#62]
Title. When I call obj::parse("thing.obj"), my code hangs forever at that line.

**Comment by phaazon** [comment]
You’re not supposed to pass a `Path` here but the actual content of your file.

However, I’m still tagging as a bug because it should return an actual parse error. Thanks for your feedback!

**Comment by phaazon** [comment]
![Screenshot 2019-09-02 at 10 25 10](https://user-images.githubusercontent.com/506592/64100521-0a087800-cd6c-11e9-8864-df835142bf50.png)

Clearly, the problem is that we’re accumulating empty objects in memory while not detecting we haven’t consumed any input. I’ll fix that.
